### ISSUE TITLE
Add diagnostic module information to sensor

### ISSUE THREAD

**Issue by jontofront** [jontofront/ecoNET-300-Home-Assistant-Integration#12]
/econet/sysParams

Keys:
controllerID
moduleASoftVer
moduleBSoftVer
moduleLambdaSoftVer
modulePanelSoftVer

**Comment by silbaums** [comment]
mega Work Thanks for Contributing! 

I also have HKS lazar SmartFire  22kW burner, 
sad that Plum dont want to be opensource and contribute to HA
