### ISSUE TITLE
[Bug]: lost sensors for buffer:(

### ISSUE THREAD

**Issue by d2ar3k** [jontofront/ecoNET-300-Home-Assistant-Integration#121]
### The problem

There are no sensors.for buffer like it was in v 1.03

### What version of ecoNET300 integration has the issue?

1.06

### What version of Home Assistant Core has the issue?

Core

### What was the last working version of ecoNET300 integration?

1.03

### Anything in the logs that might be useful for us?

```text
Nope
```

### Additional information

Nope

**Comment by jontofront** [comment]
Could you please clarify the name of the sensor you are referring to?

**Comment by d2ar3k** [comment]
sensor.plum_econet300_temperatura_bufora_dolna

And also

sensor.plum_econet300_temperatura_bufora_gorna

**Comment by jontofront** [comment]
can you send me ([jontofront@gmail.com](mailto:jontofront@gmail.com)) json file from these endpoinds? I will add
http://econet_local_ip/econet/regParams
http://econet_local_ip/econet/regParamsData
http://econet_local_ip/econet/sysParams
http://econet_local_ip/econet/rmCurrentDataParams
http://econet_local_ip/econet/rmCurrentDataParamsEdits

**Comment by d2ar3k** [comment]
Just sent teough email
Chyba możemy po polsku pisac coś mi się tak wydaje

**Comment by jontofront** [comment]
Add sensors:
tempUpperBuffer
tempLowerBuffer

if null disable it

**Comment by jontofront** [comment]
> sensor.plum_econet300_temperatura_bufora_dolna
> 
> And also
> 
> sensor.plum_econet300_temperatura_bufora_gorna

You can test it this version:
![image](https://github.com/user-attachments/assets/d47dd8a5-cd53-4aee-ac0b-7d9b3c55c828)
dev

**Comment by d2ar3k** [comment]
On my way

**Comment by d2ar3k** [comment]
Great work! Thank you.  I will use this version till next official release:)

**Comment by d2ar3k** [comment]
One other sensor is missing... HUW temperature....
You can see SET temperature but not actual

**Comment by d2ar3k** [comment]
Its "tempCWU"

**Comment by d2ar3k** [comment]
So need to go back to beta version because of this sensor missing:(

**Comment by d2ar3k** [comment]
Also noticed that sensor updates on beta version 1.03 are wayyy better than on dev version...

**Comment by jontofront** [comment]
> tempCWU

ok I add Water heater temperature - tempCWU
Tommorow realise it

**Comment by jontofront** [comment]
> One other sensor is missing... HUW temperature....
> You can see SET temperature but not actual

maybe you can make print screen?

**Comment by jontofront** [comment]
> Also noticed that sensor updates on beta version 1.03 are wayyy better than on dev version...

That might be the case, but I had to rewrite everything and clean up the old unused code. This was necessary because there are many devices with different versions. Now, it will be more flexible to continue working. Apologies for any inconvenience caused.
