### ISSUE TITLE
"[Bug]: fan power and mode are wrong

### ISSUE THREAD

**Issue by d2ar3k** [jontofront/ecoNET-300-Home-Assistant-Integration#127]
### Bug Title

Fan power nad mode wre wrong

### The problem

Hi i see that my fan is not working but in HA is showing mode WORK with power 100proc

There was no problem like this in beta 1.03

### Connected devices

- [ ] ecoMAX800 series
- [ ] ecoMAX850 series
- [ ] ecoMAX860 series
- [ ] ecoSTER
- [X] ecoNET 300

### What version of Econet300 integration has the issue?

1.07

### What version of Home Assistant Core has the issue?

Core

**Comment by d2ar3k** [comment]
By me it was showing fine but when fan stops state and power did not changed at all... they are showing last state before stop

**Comment by d2ar3k** [comment]
Same thing woth CWU pump... it is showing that pump is working when in reality it is not

**Comment by d2ar3k** [comment]
I hope that you dont mind my issues:( im not trying to complain but only finding some bugs

**Comment by jontofront** [comment]
> CWU

OK I will check `pumpCWUWorks` = True or False

**Comment by jontofront** [comment]
> By me it was showing fine but when fan stops state and power did not changed at all... they are showing last state before stop

Maybe it cache

**Comment by d2ar3k** [comment]
After HA restet all sensor showing true... i will check it after next stop.

But please dont forget to add boiler power sensor as i wrote on other message:)

**Comment by jontofront** [comment]
> After HA restet all sensor showing true... i will check it after next stop.
> 
> But please dont forget to add boiler power sensor as i wrote on other message:)

It's added in new version, also and lamda sensors

**Comment by jontofront** [comment]
> There is some bug... right now lighter is showing that it.is turned on when in reality it is off... same situation what i had with other sensors previously... they are not changing state to off... ill wait till boiler will be off to check what about fan...

You can check it directly on our local netwrok, becouse on econet24.com data is delayed.
In web url:
http://econet_local_ip/econet/regParams
http://econet_local_ip/econet/sysParams

If there more sensors which you want to see write key of sensors and value

**Comment by d2ar3k** [comment]
Thanks. There is enough sensors in yours integration.... even too much:) Only thing is problem with not changing to off when lighter stops working or fan...
For my example lighter is still on for last 7h...

**Comment by jontofront** [comment]
fix in 1.0.11 version
