### ISSUE TITLE
Issue with reading param value (editParam) from econet300

### ISSUE THREAD

**Issue by zaapp** [jontofront/ecoNET-300-Home-Assistant-Integration#26]
Set parameter works, but read is corrupted. Does it work in your implementation?
![image](https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/assets/22096395/a1e7b0bc-468b-4f4d-bd45-44421143c96b)

**Comment by zaapp** [comment]
Ahhh issue to close. I found simple solution.
`def _sync_state(self, value):
        """Sync state"""
        self._attr_native_value = value['value']
        self.async_write_ha_state()

    async def async_set_native_value(self, value: str) -> None:
        """Update the current value."""
        _LOGGER.debug("Set value: {}".format(value))

        #if value == self._attr_native_value:
        #    return

        #if value > self._attr_native_max_value:
        #    _LOGGER.warning(
        #        "Requested value: '{}' exceeds maximum allowed value: '{}'".format(value, self._attr_max_value))
        #    return

        #if value < self._attr_native_min_value:
        #    _LOGGER.warning("Requested value: '{}' is below allowed value: '{}'".format(value, self._attr_min_value))
        #    return

        if not await self._api.set_param(self.entity_description.key, int(value)):
            _LOGGER.warning("Setting value failed")
            return

        self._attr_native_value = value['value']
        self.async_write_ha_state()`

**Comment by jontofront** [comment]
I try do it but did't work, now I am testing https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/tree/edit-params for me looks work
