### ISSUE TITLE
Not working on Econet 360 controller

### ISSUE THREAD

**Issue by denveronly** [jontofront/ecoNET-300-Home-Assistant-Integration#49]
Howdy,

I was using the original old version, not forked and it was working fine.
Tried the version that is available as successor, it connects, but have like 9 entities all unavailable.
Any reason for it not to work?

**Comment by jontofront** [comment]
> Howdy,
> 
> I was using the original old version, not forked and it was working fine. Tried the version that is available as successor, it connects, but have like 9 entities all unavailable. Any reason for it not to work?

Please use the version v0.3.3
