### ISSUE TITLE
Add sensors

### ISSUE THREAD

**Issue by spawnax** [jontofront/ecoNET-300-Home-Assistant-Integration#50]
Please add sensor:
boilerPowerKW
pumpCOWorks
feederWorks
fuelStream

**Comment by jontofront** [comment]
In my output 'boilerPowerKW' and 'fuelStream' can you save output in url http://Your_Econet_local_IP/econet/regParams? and send me by email jontofront@gmail.com or to pin printscreen? output of these pramaters?

**Comment by jontofront** [comment]
Sensor added
