### ISSUE TITLE
Ecoster, internal thermostat 

### ISSUE THREAD

**Issue by plaaski** [jontofront/ecoNET-300-Home-Assistant-Integration#56]
Can you add data from internal thermostat connected to EcoNET? In my case attribute to this data is "ecoSterTemp1" and "ecoSterSetTemp1". Also would be nice to be able to change this set parameter.
Currently i'm doing this by creating sensors:
`    kociol_ecostertemp1 :
      friendly_name: Kociol Termostat
      value_template: '{{states.sensor.KOCIOL.attributes["curr"]["ecoSterTemp1"]| round (1)}}'
      device_class: temperature
      unit_of_measurement: "°C"
`

**Comment by jontofront** [comment]
Which version you are using the software? 
Can you provide more info which ecoMAX controllers you have

**Comment by plaaski** [comment]
I’m using version v0.3.3
below details of my controllers. As an external thermostat  I’m using eSTER X40.


![IMG_0536](https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/assets/59375930/21432bc1-af22-427e-8408-afe31b62f9a9)
