### ISSUE TITLE
[Bug]: wrong outside temperature

### ISSUE THREAD

**Issue by Taziff** [jontofront/ecoNET-300-Home-Assistant-Integration#72]
### The problem

After update the outside temperature is displayed incorrectly

![image](https://github.com/user-attachments/assets/000c8450-e958-452b-8ddf-d2239d3917cc)

### What version of Tech Controllers integration has the issue?

v1.0.1-beta

### What version of Home Assistant Core has the issue?

core-2024.10.2

**Comment by jontofront** [comment]
can you add diagnostic debug logs? I check data and response in my case it shows ok

**Comment by Taziff** [comment]
will this log be good?
[home-assistant_econet300_2024-10-14T14-03-44.183Z.log](https://github.com/user-attachments/files/17365039/home-assistant_econet300_2024-10-14T14-03-44.183Z.log)

**Comment by jontofront** [comment]
Can you download new version v1.0.3 and enable debug, wait 2 minutes and download it and atached there?
![Uploading image.png…]()

**Comment by Taziff** [comment]
[home-assistant_econet300_2024-10-18T06-55-20.293Z.log](https://github.com/user-attachments/files/17429625/home-assistant_econet300_2024-10-18T06-55-20.293Z.log)

**Comment by jontofront** [comment]
> [home-assistant_econet300_2024-10-18T06-55-20.293Z.log](https://github.com/user-attachments/files/17429625/home-assistant_econet300_2024-10-18T06-55-20.293Z.log)

Ok thank you,
I see your device response these '28': 0.019181668758392334 ext. temp.
Can you send me by email jontofront@gmail.com these data in separate file:
http://YourEconeDevicetIP/econet/regParamsData
http://YourEconeDevicetIP/econet/regParams
http://YourEconeDevicetIP/econet/rmCurrentDataParams
http://YourEconeDevicetIP/econet/sysParams

I will check version of software econet and also model and response data

**Comment by jontofront** [comment]
Significant changes have been made after discovering that the data source IDs (sensor keys) vary depending on the connected devices. The code has been improved accordingly.

Currently, not all previous sensors are included, but they will be gradually added back over time.

Thank you for your understanding!
