### ISSUE TITLE
[Bug]: After update to 1.0.0, ecosol300 can't be load

### ISSUE THREAD

**Issue by TWIX99b** [jontofront/ecoNET-300-Home-Assistant-Integration#79]
### The problem

I manually created the sensors for t1, t2, t3, and t4 in version 0.33. Since updating to version 1.0.0, the integration can no longer be loaded. After further investigation, I found out that changing the API query to /regParamsData is not possible for the ecoSOL, as this path does not exist for this device.

### What version of ecoNET300 integration has the issue?

3.2.3827

### What version of Home Assistant Core has the issue?

core-2024.10.2

### What was the last working version of ecoNET300 integration?

0.3.3

**Comment by jontofront** [comment]
I can separate old version code to another repo for Ecosol. I am not suing ecosol, fo ecosol for me need more infromation.

**Comment by jontofront** [comment]
for more investigation, can you send me ([jontofront@gmail.com](mailto:jontofront@gmail.com)) json file from these endpoinds?

http://econet_local_ip/econet/regParams
http://econet_local_ip/regParamsData
http://econet_local_ip/econet/sysParams
http://econet_local_ip/econet/rmCurrentDataParams
http://econet_local_ip/econet/rmCurrentDataParamsEdits

**Comment by jontofront** [comment]
Automatic closing. If needed, please attach the log and create a new task.
