### ISSUE TITLE
[Bug]: Boiler staus keys map

### ISSUE THREAD

**Issue by walek79** [jontofront/ecoNET-300-Home-Assistant-Integration#81]
### The problem

Hello,
I have a problem with the status of the boiler entity, during operation it shows "fire_up" all the time

**/const.py**
# Boiler staus keys map
# boiler mode names from  endpoint http://LocalIP/econet/rmParamsEnums?
OPERATION_MODE_NAMES = {
    0: "off",
    1: "fire_up",
    2: "fire_up",
    3: "work",
    4: "supervision",
    5: "halted",
    6: "stop",
    7: "burning_off",
    8: "manual",
    9: "alarm",
    10: "unsealing",
    11: "chimney",
    12: "stabilization",
    13: "no_transmission",

**http://IP/econet/rmParamsEnums**
 {
      "values": [
        "TURNED OFF",
        "FIRE UP",
        "OPERATION",
        "SUPERVISION",
        "BURNING OFF",
        "STOP",
        "MANUAL",
        "ALARM",
        "CLEANING",
        "CHIMNEY SWEEP",
        "INCANDESCENCE",
        "ACTIVACTION",
        "NO TRANSMISSION"
      ],

 

### What version of ecoNET300 integration has the issue?

1.0.3-beta

### What version of Home Assistant Core has the issue?

core-2024.10.3

### Additional information

**http://IP/econet/sysParams**
  "login": "admin",
  "ecosrvAddr": "econet24.com",
  "etConfVer": null,
  "ecosrvHttps": true,
  "history": [],
  "settingsVer": 72475,
  "softVer": "3.2.3819",
  "routerType": "mr3020-v3",
  "protocolType": "em",
  "controllerID": "ecoMAX860P2-N TOUCH",
  "prodLogo": 41,
  "regImgID": 2,
  "regType": 0,
  "regProd": 41,
  "moduleASoftVer": "20.21.95.P1",
  "moduleBSoftVer": null,
  "moduleCSoftVer": null,
  "moduleLambdaSoftVer": null,
  "moduleEcoSTERSoftVer": null,
  "modulePanelSoftVer": "20.11.17",
  "schemaID": 23,
  "panelVer": null

**Comment by jontofront** [comment]
OK, thanks I add it

**Comment by walek79** [comment]
The operating mode is displayed correctly, thank you

![image](https://github.com/user-attachments/assets/99850aa7-39c9-4bc2-b478-18307edfd292)
