### ISSUE TITLE
[Bug]: Unexpected error

### ISSUE THREAD

**Issue by thiamark** [jontofront/ecoNET-300-Home-Assistant-Integration#82]
### The problem

I try to connect to ecoNET300 and i got an error. Unexpected Error. The host should be the ip assigned to the Home Assistant yes? my full ip for home assistant looks like this 123.123.1.1/24 i've try with 123.123.1.1 , 123.123.1.2 until 10 and nothing. even with the domain name homeassistant and nothing. Am i doing something wrong?

### What version of ecoNET300 integration has the issue?

v1.0.3-beta

### What version of Home Assistant Core has the issue?

core-2024.10.3

**Comment by jontofront** [comment]
You should know the IP address [of the econet ](https://thermostahl.ro/wp-content/uploads/2020/08/ecoNET300_DTR_1.0_ENG.pdf).  Do you have such a device?
If yes you can find you device IP in interbnet provider router.
