### ISSUE TITLE
[Bug]: Fuel level

### ISSUE THREAD

**Issue by Ognyan72** [jontofront/ecoNET-300-Home-Assistant-Integration#83]
### The problem

Hello, after the update the fuel level is no longer read?

### What version of ecoNET300 integration has the issue?

1.0.3-beta

### What version of Home Assistant Core has the issue?

core-2024.10.4

**Comment by jontofront** [comment]
Fuel level mus read

**Comment by Ognyan72** [comment]
> Fuel level must read please check again

I tried again and again but no result. It shows me this from the picture
![Fuel_level](https://github.com/user-attachments/assets/7e6a0d89-302e-46bf-b881-9fcddb41a800)

**Comment by jontofront** [comment]
What version of controller you have:
![image](https://github.com/user-attachments/assets/c897178a-c544-4a40-9660-cfd917dd61aa)

**Comment by Ognyan72** [comment]
This is my controller
![Untitled](https://github.com/user-attachments/assets/d3993913-a5bc-42b9-aed2-974abdcd7791)

**Comment by jontofront** [comment]
for more investigation, can you send me (jontofront@gmail.com) json file from these endpoinds?

http://econet_local_ip/econet/regParams
http://econet_local_ip/regParamsData
http://econet_local_ip/econet/sysParams
http://econet_local_ip/econet/rmCurrentDataParams
http://econet_local_ip/econet/rmCurrentDataParamsEdits

**Comment by jontofront** [comment]
Significant changes have been made after discovering that the data source IDs (sensor keys) vary depending on the connected devices. The code has been improved accordingly.

Currently, not all previous sensors are included, but they will be gradually added back over time.

Thank you for your understanding!

**Comment by Ognyan72** [comment]
The interesting thing is that when I install a new version (1.0.5 or 1.0.6. the fuel level is displayed correctly, but the other sensors become unknown. With the old version all sensors are displayed correctly, but the fuel level is unknown

**Comment by jontofront** [comment]
We have rewritten the code logic to make it more flexible. I will add the missing sensors later you can downgratre if you want
